# Generated by Django 4.2.6 on 2023-12-02 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulator.item')),
                ('devise', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'poste',
                'verbose_name_plural': 'postes',
            },
            bases=('simulator.item',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('valeur', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='poste',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created_at',), 'verbose_name': 'AbstactItem'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='object_id',
            new_name='object_id_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='devis',
        ),
        migrations.RemoveField(
            model_name='item',
            name='poste',
        ),
        migrations.AddField(
            model_name='item',
            name='content_type_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='entite_1', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='content_type_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='entite_2', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='object_id_2',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulator.service')),
                ('duration_days', models.IntegerField(default=30, verbose_name='duree de devis (jours)')),
            ],
            options={
                'abstract': False,
            },
            bases=('simulator.service',),
        ),
        migrations.DeleteModel(
            name='DemandeDevisSimulee',
        ),
        migrations.DeleteModel(
            name='Poste',
        ),
    ]
