# Generated by Django 4.2.6 on 2023-12-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devis',
            options={'verbose_name': 'Devis', 'verbose_name_plural': 'Devis'},
        ),
    ]
