# Generated by Django 4.2.6 on 2023-12-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_alter_devis_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='titre',
        ),
    ]
