# Generated by Django 4.2.6 on 2023-12-02 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulator', '0002_posteitem_service_remove_poste_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(choices=[('ACT', 'Encours'), ('CLO', 'cloturé')], default='ACT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_out', models.BooleanField(default=False, verbose_name='checked out')),
                ('comment', models.TextField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
                'ordering': ('-created_at',),
            },
        ),
    ]
