# Generated by Django 4.2.9 on 2024-01-19 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_devis_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SousRubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.rubrique')),
            ],
        ),
        migrations.CreateModel(
            name='ChargesFonctionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire_mensuel', models.FloatField(default=0)),
                ('quantite', models.FloatField(default=0)),
                ('nombre_mois_annuel', models.FloatField(default=12)),
                ('sous_rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.sousrubrique')),
            ],
        ),
    ]
