# Generated by Django 4.2.6 on 2023-10-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedecandidature',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Les réferences de la societe'),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='status',
            field=models.CharField(choices=[('OP', 'Encours'), ('FR', 'Cloturé'), ('AB', 'Abondonné'), ('EA', 'En attente')], default='1', max_length=30, verbose_name='Status :'),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='visite',
            field=models.BooleanField(default=1, verbose_name='Visite effectuée'),
        ),
        migrations.AlterField(
            model_name='lignedecandidature',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lignedecandidature',
            name='contacte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lignedecandidature',
            name='recommande_par',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lignedecandidature',
            name='societe',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lignedecandidature',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone'),
        ),
    ]
