# Generated by Django 4.2.6 on 2023-10-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0002_lignedecandidature_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='photo',
        ),
        migrations.AlterField(
            model_name='lignedecandidature',
            name='visite',
            field=models.BooleanField(default='', verbose_name='Visite effectuée'),
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('photos', models.FileField(upload_to='upload/')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copro.residence')),
            ],
        ),
    ]
