# Generated by Django 4.2.6 on 2023-10-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0009_residence_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='photo',
        ),
    ]
