# Generated by Django 4.2.6 on 2023-10-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0010_remove_residence_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='image',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
    ]
