# Generated by Django 4.2.6 on 2023-10-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0022_lignedecandidature_notation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedecandidature',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lignedecandidature',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Observations'),
        ),
    ]
