# Generated by Django 4.2.6 on 2023-10-31 13:32

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0023_lignedecandidature_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedecandidature',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
