# Generated by Django 4.2.6 on 2023-10-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0007_pjointe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pjointe',
            old_name='documents',
            new_name='piece',
        ),
    ]
