# Generated by Django 4.2.6 on 2023-10-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0011_residence_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedecandidature',
            name='budget_global',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='offre',
            field=models.BooleanField(default=False, verbose_name='Offre du syndic'),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='remuneration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lignedecandidature',
            name='candidat',
            field=models.BooleanField(default=False, verbose_name='Ajouter a la liste des Candidats'),
        ),
        migrations.AlterField(
            model_name='lignedecandidature',
            name='visite',
            field=models.BooleanField(default=False, verbose_name='Visite effectuée'),
        ),
    ]
