# Generated by Django 4.2.6 on 2023-10-28 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0012_lignedecandidature_budget_global_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Prestation de service')),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etude',
            name='type_presta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='copro.prestationservice'),
        ),
    ]
