# Generated by Django 4.2.6 on 2023-10-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0014_alter_etude_type_presta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etude',
            name='type_presta',
        ),
    ]
