# Generated by Django 4.2.6 on 2023-10-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0019_prestationservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignedecandidature',
            name='site_web',
        ),
    ]
