# Generated by Django 4.2.6 on 2023-12-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartcom', '0002_alter_itemarticle_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemarticle',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='itemarticle',
            name='object_id',
        ),
    ]
