# Generated by Django 4.2.6 on 2023-12-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartcom', '0006_remove_itemarticle_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartof',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
