# Generated by Django 4.2.9 on 2024-01-25 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartcom', '0007_alter_cartof_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartof',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='carts', to='cartcom.itemarticle'),
        ),
        migrations.AlterField(
            model_name='cartof',
            name='statut',
            field=models.CharField(choices=[('ACT', 'En cours'), ('CLO', 'Cloturé')], default='ACT', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemarticle',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_item', to='cartcom.cartof'),
        ),
    ]
