# Generated by Django 4.2.9 on 2024-01-30 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartcom', '0008_cartof_items_alter_cartof_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemarticle',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cartcom.cartof'),
        ),
    ]
