# Generated by Django 4.2.6 on 2023-11-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.BooleanField(verbose_name='Votez'),
        ),
    ]
