# Generated by Django 4.2.6 on 2023-11-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_choice_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Votez '),
        ),
    ]
