# Generated by Django 4.2.6 on 2023-11-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choice_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.CharField(choices=[('EXC', 'Excellent'), ('MOY', 'Moyen'), ('NUL', 'Mediocre'), ('AVO', 'A voir'), ('EPR', 'Epouvé')], max_length=50, verbose_name='Votez '),
        ),
    ]
