# Generated by Django 4.2.6 on 2023-11-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_choice_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualifiedChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('choice', models.CharField(max_length=50)),
                ('positif', models.BooleanField(verbose_name='qualite positif')),
                ('valeur', models.PositiveIntegerField(verbose_name='sa valeur')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('SAT', 'Questionnaire Satisfaction'), ('ELC', 'Questionnaire Electorale'), ('CAND', 'Questionnaire Candidature')], default='CAND', max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.CharField(choices=[('BLANC', 'Ne se prononce pas'), ('1_EXC', 'Excellent'), ('1_MOY', 'Moyen'), ('0_NUL', 'Mediocre'), ('1_SUFF', 'Suffisant(e)'), ('0_SUFF', 'Insuffisant(e)'), ('1_COR', 'Correcte'), ('0_ELV', 'Elevé')], default=1, max_length=50, verbose_name='Votez '),
        ),
    ]
