# Generated by Django 4.2.6 on 2023-11-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_choice_qualifiedchoice_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.ManyToManyField(to='polls.qualifiedchoice', verbose_name='Votez '),
        ),
    ]
