# Generated by Django 4.2.6 on 2023-11-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_uservote_delete_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Campagne',
        ),
        migrations.RenameField(
            model_name='campagne',
            old_name='question_text',
            new_name='titre',
        ),
    ]
