# Generated by Django 4.2.6 on 2023-11-30 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0010_remove_uservote_choice_text_uservote_campagne'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservote',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together={('campagne', 'created_by', 'question', 'vote')},
        ),
    ]
