# Generated by Django 4.2.6 on 2023-10-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0004_rename_photos_piece_pieces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='pieces',
            new_name='piece',
        ),
    ]
