# Generated by Django 4.2.6 on 2023-10-28 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0013_prestationservice_lignedecandidature_site_web_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etude',
            name='type_presta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copro.prestationservice'),
        ),
    ]
