# Generated by Django 4.2.6 on 2023-10-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0017_remove_etude_type_presta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrestationService',
        ),
    ]
