# Generated by Django 4.2.6 on 2023-10-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0021_lignedecandidature_site_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedecandidature',
            name='notation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lignedecandidature',
            name='adresse',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
