# Generated by Django 4.2.6 on 2023-11-04 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('copro', '0024_alter_lignedecandidature_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Contacte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentJoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pj_file', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='date debut')),
                ('end', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date fin')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('closed', models.DateTimeField(blank=True, null=True, verbose_name='closed on')),
            ],
            options={
                'verbose_name': 'Evenement',
                'verbose_name_plural': 'Evenements',
                'ordering': ('-start',),
                'get_latest_by': '-start',
            },
        ),
        migrations.CreateModel(
            name='GDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(help_text='Description', verbose_name='description')),
                ('urgency', models.CharField(choices=[('FAIBLE', 'pas important pas urgent'), ('CRITIQUE', 'important et pas Urgent'), ('MOYEN', 'uregnt et pas importance'), ('URGENT', 'Urgent et Important')], default='MOYEN', max_length=20, verbose_name='urgency')),
                ('status', models.CharField(choices=[('NOUVEAU', 'nouveau'), ('ENCOURS', 'encours'), ('RESOLUE', 'resolue'), ('CLOTUREE', 'cloturee'), ('ANNULEE', 'annulee'), ('ENATTENTE', 'en attente')], default='NOUVEAU', max_length=20, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified on')),
                ('closed', models.DateTimeField(blank=True, null=True, verbose_name='closed on')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('schedule_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='copro_docum_content_320986_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pj_file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.AddField(
            model_name='document',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='do_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='do_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_basename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='initial_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='thumbnail_file',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='copro.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='copro.residence', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='gdocument',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='gdocument',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='copro.document', verbose_name='piece jointe'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evenement',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='copro.category', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='documentjoint',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='copro.category'),
        ),
        migrations.AddIndex(
            model_name='documentjoint',
            index=models.Index(fields=['content_type', 'object_id'], name='copro_docum_content_c2d220_idx'),
        ),
    ]
