# Generated by Django 4.2.6 on 2023-11-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0026_remove_lignedecandidature_candidat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etude',
            name='type_presta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='copro.prestationservice'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PJEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('piece', models.FileField(upload_to='upload/')),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copro.etude')),
            ],
        ),
    ]
