# Generated by Django 4.2.6 on 2023-11-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0027_etude_type_presta_pjetude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etude',
            name='type_presta',
        ),
    ]
