# Generated by Django 4.2.6 on 2023-11-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0028_remove_etude_type_presta'),
    ]

    operations = [
        migrations.AddField(
            model_name='etude',
            name='type_presta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='copro.prestationservice'),
        ),
    ]
