# Generated by Django 4.2.6 on 2023-11-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0029_etude_type_presta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PJEtude',
        ),
    ]
