# Generated by Django 4.2.6 on 2023-11-07 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0030_delete_pjetude'),
    ]

    operations = [
        migrations.CreateModel(
            name='PJEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('piece', models.FileField(upload_to='upload/')),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copro.etude')),
            ],
        ),
    ]
