# Generated by Django 4.2.6 on 2023-11-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0031_pjetude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pjetude',
            old_name='candidature',
            new_name='etude',
        ),
    ]
