# Generated by Django 4.2.6 on 2023-11-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0032_rename_candidature_pjetude_etude'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedecandidature',
            name='budget_jardinage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='budget_securite',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
