# Generated by Django 4.2.6 on 2023-11-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0033_lignedecandidature_budget_jardinage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedecandidature',
            name='offre',
            field=models.PositiveBigIntegerField(default=False, verbose_name='Offre du syndic'),
        ),
    ]
