# Generated by Django 4.2.6 on 2023-11-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0035_pjevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pjevent',
            old_name='etude',
            new_name='event',
        ),
    ]
