# Generated by Django 4.2.6 on 2023-11-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0036_rename_etude_pjevent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedecandidature',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
