# Generated by Django 4.2.6 on 2023-11-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0037_lignedecandidature_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignedecandidature',
            name='offre',
        ),
    ]
