# Generated by Django 4.2.6 on 2023-11-13 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copro', '0038_remove_lignedecandidature_offre'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='created',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pjetude',
            name='created',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pjetude',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pjointe',
            name='created',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pjointe',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
