# Generated by Django 4.2.6 on 2023-11-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0039_piece_created_piece_created_by_pjetude_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Creation'),
        ),
        migrations.AddField(
            model_name='pjetude',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Creation'),
        ),
        migrations.AddField(
            model_name='pjointe',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Creation'),
        ),
    ]
