# Generated by Django 4.2.6 on 2023-11-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0043_pjevent_created_pjevent_created_by_pjevent_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='created',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='pjetude',
            name='created',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='pjevent',
            name='created',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='pjointe',
            name='created',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
