# Generated by Django 4.2.6 on 2023-12-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0044_lignedecandidature_budget_agent_suivi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedecandidature',
            name='budget_maitre_nageur',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
