# Generated by Django 4.2.6 on 2023-12-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0045_lignedecandidature_budget_maitre_nageur'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedecandidature',
            name='contrat_engagement',
            field=models.BooleanField(default=False, verbose_name='contrat engagement '),
        ),
    ]
