# Generated by Django 4.2.6 on 2023-12-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0046_lignedecandidature_contrat_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedecandidature',
            name='agence_local',
            field=models.BooleanField(default=False, verbose_name='contrat engagement '),
        ),
    ]
