# Generated by Django 4.2.6 on 2023-12-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0047_lignedecandidature_agence_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignedecandidature',
            name='agence_local',
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='agence_locale',
            field=models.BooleanField(default=False, verbose_name='Agence locale'),
        ),
    ]
