# Generated by Django 4.2.6 on 2023-12-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0050_lignedecandidature_consommation_eau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedecandidature',
            name='propostion_recouverement',
            field=models.BooleanField(default=False, verbose_name='Proposition de recouvrement '),
        ),
    ]
