# Generated by Django 4.2.6 on 2023-12-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0051_alter_lignedecandidature_propostion_recouverement'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedecandidature',
            name='anciennete',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anciennete entreprise'),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='budget_prev_2024',
            field=models.BooleanField(default=False, verbose_name='Budget Previsionnel 2024'),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='budget_prev_2025',
            field=models.BooleanField(default=False, verbose_name='Budget Previsionnel 2024'),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='model_prestataires_ext',
            field=models.BooleanField(default=False, verbose_name='Model prestataires externe'),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='process_suivi_prests',
            field=models.BooleanField(default=False, verbose_name='Processus suivi prestataires'),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='ressource_sur_place',
            field=models.BooleanField(default=False, verbose_name='Ressource sur place'),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='taille_entreprise',
            field=models.IntegerField(blank=True, null=True, verbose_name='Taille entreprise'),
        ),
        migrations.AlterField(
            model_name='lignedecandidature',
            name='agence_locale',
            field=models.BooleanField(default=False, verbose_name='Siege a Marrakech'),
        ),
    ]
