# Generated by Django 4.2.6 on 2023-12-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0052_lignedecandidature_anciennete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedecandidature',
            name='avis_negatif',
            field=models.IntegerField(blank=True, null=True, verbose_name='Avis Negatif'),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='avis_positif',
            field=models.IntegerField(blank=True, null=True, verbose_name='Avis Positif'),
        ),
    ]
