# Generated by Django 4.2.6 on 2023-12-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0053_lignedecandidature_avis_negatif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedecandidature',
            name='budget_prev_2025',
            field=models.BooleanField(default=False, verbose_name='Budget Previsionnel 2025'),
        ),
        migrations.AlterField(
            model_name='lignedecandidature',
            name='ressource_sur_place',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
