# Generated by Django 4.2.6 on 2023-12-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0054_alter_lignedecandidature_budget_prev_2025_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedecandidature',
            name='effectif_sur_place',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Effectif sur place'),
        ),
        migrations.AlterField(
            model_name='lignedecandidature',
            name='ressource_sur_place',
            field=models.BooleanField(default=False, verbose_name='Ressource sur place'),
        ),
    ]
