# Generated by Django 4.2.6 on 2023-12-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0055_lignedecandidature_effectif_sur_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignedecandidature',
            name='effectif_sur_place',
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='agent_suivi_local',
            field=models.PositiveIntegerField(default=0, verbose_name='Agent suivi sur place'),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='effectif_agent_polyvalent',
            field=models.PositiveIntegerField(default=0, verbose_name='Agent polyvalent'),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='effectif_agent_proprete',
            field=models.PositiveIntegerField(default=0, verbose_name='agent proprete'),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='effectif_jardinage',
            field=models.PositiveIntegerField(default=0, verbose_name='Effectif jardinage'),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='effectif_maitre_nageur',
            field=models.PositiveIntegerField(default=0, verbose_name='maitre_nageur polyvalent'),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='effectif_piciniste',
            field=models.PositiveIntegerField(default=0, verbose_name='Piciniste'),
        ),
        migrations.AddField(
            model_name='lignedecandidature',
            name='effectif_securite',
            field=models.PositiveIntegerField(default=0, verbose_name='Effectif sécurité'),
        ),
    ]
