# Generated by Django 4.2.6 on 2024-01-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro', '0056_remove_lignedecandidature_effectif_sur_place_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignedecandidature',
            old_name='provison_investissement',
            new_name='provision_investissement',
        ),
        migrations.AlterField(
            model_name='lignedecandidature',
            name='effectif_maitre_nageur',
            field=models.PositiveIntegerField(default=0, verbose_name='maitre_nageur'),
        ),
    ]
